
import { Product, LifecycleStatus } from './types';

export const LIFECYCLE_STATUS_OPTIONS: LifecycleStatus[] = [
  LifecycleStatus.DESIGN,
  LifecycleStatus.TESTING,
  LifecycleStatus.IN_PRODUCTION,
  LifecycleStatus.OBSOLETE,
];

export const MATERIALS: string[] = [
    'Aluminum 6061-T6',
    'Stainless Steel 304',
    'Titanium Grade 5',
    'ABS Plastic',
    'Polycarbonate',
    'Carbon Fiber',
    'Copper C110'
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'pid-1',
    gtin: '01234567890123',
    partNumber: 'BRK-001-AL',
    name: 'Main Mounting Bracket',
    description: 'A precision-machined aluminum bracket for core chassis assembly. Features reinforced mounting points and an anodized finish for corrosion resistance. Critical component for structural integrity.',
    material: 'Aluminum 6061-T6',
    dimensions: { length: 150, width: 75, height: 50, unit: 'mm' },
    weight: { value: 0.25, unit: 'kg' },
    lifecycleStatus: LifecycleStatus.IN_PRODUCTION,
    supplier: 'Precision Parts Inc.',
    manufacturer: 'AluWorks GmbH',
    dataOwner: 'engineering@example.com',
    sourceSystem: 'ERP-System-A',
    creationDate: '2023-01-15T10:00:00Z',
    lastModified: '2023-10-28T14:30:00Z',
    imageUrl: 'https://picsum.photos/seed/bracket/600/400',
  },
  {
    id: 'pid-2',
    gtin: '98765432109876',
    partNumber: 'GEAR-03-SS',
    name: 'High-Torque Drive Gear',
    description: 'A hardened stainless steel gear for the primary transmission assembly. Teeth are precision-cut for minimal backlash and optimal power transfer.',
    material: 'Stainless Steel 304',
    dimensions: { length: 45, width: 45, height: 20, unit: 'mm' },
    weight: { value: 0.18, unit: 'kg' },
    lifecycleStatus: LifecycleStatus.IN_PRODUCTION,
    supplier: 'Global Gears Ltd.',
    manufacturer: 'Global Gears Ltd.',
    dataOwner: 'manufacturing@example.com',
    sourceSystem: 'PLM-System-B',
    creationDate: '2022-11-20T09:00:00Z',
    lastModified: '2023-09-15T11:00:00Z',
    imageUrl: 'https://picsum.photos/seed/gear/600/400',
  },
  {
    id: 'pid-3',
    gtin: '55544433322211',
    partNumber: 'ENC-01-PC',
    name: 'Protective Enclosure Top',
    description: 'A durable polycarbonate enclosure top, transparent for visual inspection of internal components. Designed for impact resistance and environmental sealing.',
    material: 'Polycarbonate',
    dimensions: { length: 200, width: 150, height: 25, unit: 'mm' },
    weight: { value: 0.35, unit: 'kg' },
    lifecycleStatus: LifecycleStatus.DESIGN,
    supplier: 'PlasticsForm Co.',
    manufacturer: 'PlasticsForm Co.',
    dataOwner: 'design@example.com',
    sourceSystem: 'CAD-System-C',
    creationDate: '2023-08-01T16:00:00Z',
    lastModified: '2023-11-05T18:00:00Z',
    imageUrl: 'https://picsum.photos/seed/enclosure/600/400',
  },
  {
    id: 'pid-4',
    gtin: '11223344556677',
    partNumber: 'SHAFT-TI-007',
    name: 'Titanium Drive Shaft',
    description: '',
    material: 'Titanium Grade 5',
    dimensions: { length: 300, width: 15, height: 15, unit: 'mm' },
    weight: { value: 0.1, unit: 'kg' },
    lifecycleStatus: LifecycleStatus.TESTING,
    supplier: 'Advanced Materials Corp',
    manufacturer: 'Advanced Materials Corp',
    dataOwner: 'testing@example.com',
    sourceSystem: 'Manual Entry',
    creationDate: '2023-06-10T12:00:00Z',
    lastModified: '2023-10-10T10:10:00Z',
    imageUrl: 'https://picsum.photos/seed/shaft/600/400',
  },
  {
    id: 'pid-5',
    gtin: '00001111222233',
    partNumber: 'OBS-VALVE-01',
    name: 'Legacy Flow Valve',
    description: 'An obsolete brass flow valve from a previous generation product. No longer in production. Maintained for historical reference and servicing of old units.',
    material: 'Brass',
    dimensions: { length: 80, width: 60, height: 110, unit: 'mm' },
    weight: { value: 1.2, unit: 'kg' },
    lifecycleStatus: LifecycleStatus.OBSOLETE,
    supplier: 'N/A',
    manufacturer: 'OldTech Industries',
    dataOwner: 'archive@example.com',
    sourceSystem: 'Archived Database',
    creationDate: '2015-03-01T00:00:00Z',
    lastModified: '2020-01-01T00:00:00Z',
    imageUrl: 'https://picsum.photos/seed/valve/600/400',
  },
];
